export const squares = [
  [
    {
      id: 0,
      position: [0, 0],
      type: "special",
      color: "white",
      activated: false,
    },
    {
      id: 1,
      position: [0, 1],
      type: "default",
      color: "white",
      activated: false,
    },
    {
      id: 2,
      position: [0, 2],
      type: "default",
      color: "white",
      activated: false,
    },
    {
      id: 3,
      position: [1, 0],
      type: "default",
      color: "white",
      activated: false,
    },
    {
      id: 4,
      position: [1, 1],
      type: "default",
      color: "white",
      activated: false,
    },
    {
      id: 5,
      position: [1, 2],
      type: "default",
      color: "white",
      activated: false,
    },
    {
      id: 6,
      position: [2, 0],
      type: "default",
      color: "white",
      activated: false,
    },
    {
      id: 7,
      position: [2, 1],
      type: "default",
      color: "white",
      activated: false,
    },
    {
      id: 8,
      position: [2, 2],
      type: "default",
      color: "white",
      activated: false,
    },
  ],
  [
    {
      id: 0,
      position: [0, 0],
      type: "default",
      color: "tertiary",
      activated: false,
    },
    {
      id: 1,
      position: [0, 1],
      type: "default",
      color: "secondary",
      activated: false,
    },
    {
      id: 2,
      position: [0, 2],
      type: "special",
      color: "primary",
      activated: false,
    },
    {
      id: 3,
      position: [1, 0],
      type: "default",
      color: "secondary",
      activated: false,
    },
    {
      id: 4,
      position: [1, 1],
      type: "default",
      color: "tertiary",
      activated: false,
    },
    {
      id: 5,
      position: [1, 2],
      type: "default",
      color: "secondary",
      activated: false,
    },
    {
      id: 6,
      position: [2, 0],
      type: "default",
      color: "primary",
      activated: false,
    },
    {
      id: 7,
      position: [2, 1],
      type: "default",
      color: "secondary",
      activated: false,
    },
    {
      id: 8,
      position: [2, 2],
      type: "default",
      color: "primary",
      activated: false,
    },
  ],
  [
    {
      id: 0,
      position: [0, 0],
      type: "default",
      color: "tertiary",
      activated: false,
    },
    {
      id: 1,
      position: [0, 1],
      type: "default",
      color: "primary",
      activated: false,
    },
    {
      id: 2,
      position: [0, 2],
      type: "default",
      color: "tertiary",
      activated: false,
    },
    {
      id: 3,
      position: [1, 0],
      type: "default",
      color: "primary",
      activated: false,
    },
    {
      id: 4,
      position: [1, 1],
      type: "special",
      color: "tertiary",
      activated: false,
    },
    {
      id: 5,
      position: [1, 2],
      type: "default",
      color: "primary",
      activated: false,
    },
    {
      id: 6,
      position: [2, 0],
      type: "default",
      color: "tertiary",
      activated: false,
    },
    {
      id: 7,
      position: [2, 1],
      type: "default",
      color: "primary",
      activated: false,
    },
    {
      id: 8,
      position: [2, 2],
      type: "default",
      color: "tertiary",
      activated: false,
    },
  ],
  [
    {
      id: 0,
      position: [0, 0],
      type: "default",
      color: "secondary",
      activated: false,
    },
    {
      id: 1,
      position: [0, 1],
      type: "default",
      color: "tertiary",
      activated: false,
    },
    {
      id: 2,
      position: [0, 2],
      type: "default",
      color: "secondary",
      activated: false,
    },
    {
      id: 3,
      position: [1, 0],
      type: "default",
      color: "primary",
      activated: false,
    },
    {
      id: 4,
      position: [1, 1],
      type: "default",
      color: "secondary",
      activated: false,
    },
    {
      id: 5,
      position: [1, 2],
      type: "default",
      color: "tertiary",
      activated: false,
    },
    {
      id: 6,
      position: [2, 0],
      type: "special",
      color: "secondary",
      activated: false,
    },
    {
      id: 7,
      position: [2, 1],
      type: "default",
      color: "primary",
      activated: false,
    },
    {
      id: 8,
      position: [2, 2],
      type: "default",
      color: "secondary",
      activated: false,
    },
  ],
  [
    {
      id: 0,
      position: [0, 0],
      type: "default",
      color: "tertiary",
      activated: false,
    },
    {
      id: 1,
      position: [0, 1],
      type: "default",
      color: "primary",
      activated: false,
    },
    {
      id: 2,
      position: [0, 2],
      type: "default",
      color: "secondary",
      activated: false,
    },
    {
      id: 3,
      position: [1, 0],
      type: "default",
      color: "secondary",
      activated: false,
    },
    {
      id: 4,
      position: [1, 1],
      type: "default",
      color: "tertiary",
      activated: false,
    },
    {
      id: 5,
      position: [1, 2],
      type: "default",
      color: "tertiary",
      activated: false,
    },
    {
      id: 6,
      position: [2, 0],
      type: "default",
      color: "secondary",
      activated: false,
    },
    {
      id: 7,
      position: [2, 1],
      type: "default",
      color: "primary",
      activated: false,
    },
    {
      id: 8,
      position: [2, 2],
      type: "special",
      color: "tertiary",
      activated: false,
    },
  ],
];
